<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>fr.francetv.foundation</groupId>
    <artifactId>foundation-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../foundation-parent/pom.xml</relativePath>
  </parent>

  <artifactId>foundation-sample-service</artifactId>

  <name>foundation-sample-service</name>
  <description>Sample service - demonstrates usage of foundation platform starters</description>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>fr.francetv.foundation</groupId>
        <artifactId>foundation-bom</artifactId>
        <version>${project.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>fr.francetv.foundation</groupId>
      <artifactId>foundation-core-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>fr.francetv.foundation</groupId>
      <artifactId>foundation-api-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>fr.francetv.foundation</groupId>
      <artifactId>foundation-logging-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>fr.francetv.foundation</groupId>
      <artifactId>foundation-observability-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>fr.francetv.foundation</groupId>
      <artifactId>foundation-security-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
    </dependency>
    <dependency>
      <groupId>fr.francetv.foundation</groupId>
      <artifactId>foundation-test-starter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

</project>
